#!/usr/bin/python

import sys
import yaml




class Business(object):
    def __init__(self, build_file):
        self.pip = ""
        self.build_file = build_file
        self.config = ""

    def _parse_config_yml(self):
        pass


    def _parse_build_yml(self):
        with open(self.build_file, 'r') as stream:
            try:
                self.pipe = yaml.load(stream)
            except yaml.YAMLError as exc:
                print(exc)
                sys.exit(1)

    def _preflight(self):
        self.bamboo = BambooAPIClient(user= , password= , host= ) 
        pass

    def bambooBuildAndWait(self, waiting_queue):
        """
        Queue up bamboo build jobs 
        """
        build_queue = []

        for item in list(waiting_queue):
            print 'adding to queue', item
            build_key = bamboo.queue_build(item)['buildResultKey']
            build_queue.append(build_key)
            waiting_queue.remove(item)

        while len(build_queue) > 0:
            for item in list(build_queue):
                state = bamboo.get_results(item)['lifeCycleState']
                print item, state
                if state == 'Finished': 
                    build_queue.remove(item)
            time.sleep(1)


    def bash(self):
        """
        Run a command using the bash shell
        """
        pass


    def run(self):
        """
        Main entry point
        """
        self._parse_config_yml()
        self._parse_build_yml()
        self._preflight()
        for segment in self.pipe:
            for key, value in segment.iteritems():
                getattr(self, key)(value['jobs'])



if __name__ == '__main__':
    Business(sys.argv[1]).run()


